apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

namePrefix: prod-

commonLabels:
  environment: prod
  team: platform

resources:
  - ../base_deployment
  - postgres-service.yaml
  - postgres-statefulset.yaml

configMapGenerator:
  - name: calculadora-config
    behavior: merge
    literals:
      - ENVIRONMENT=development
      - VERSION=prod-latest
      - LOG_LEVEL=debug
      - FEATURE_FLAG_NEW_UI=true

replicas:
  - name: calculadora
    count: 3

images:
  - name: calculadora
    newTag: latest

secretGenerator:
  - name: calculadora-db-secret
    literals:
      - POSTGRES_USER=calc
      - POSTGRES_PASSWORD=calc
      - POSTGRES_DB=calculadora
    behavior: create
